version: '3.9'

services:
  database:
    image: 'mysql:8.0.30'
    ports:
      - '3336:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_docker
      - MYSQL_DATABASE=nest_authentication_db
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$root_password_docker"]
      interval: 5s
      timeout: 20s
      retries: 4
      start_period: 10s
  # api:
  #   build:
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     database:

volumes:
  mysqldata:
    